--"Buffer switching
vim.keymap.set({ 'n', 'v', 'o' }, '<space>n', ':bnext<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<space>p', ':bprevious<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<space>x', ':bdelete<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<space>i', ':bfirst<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<space>l', ':blast<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<space>b', ':b#<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<space>g', ':LualineBuffersJump! ')
vim.keymap.set({ 'n', 'v', 'o' }, '<C-f>', ':NvimTreeToggle<cr>')
vim.keymap.set({ 'n', 'v', 'o' }, '<C-w>', ':nohl<cr>')

vim.keymap.set('n', "C-k", ":wincmd k<CR>")
vim.keymap.set('n', "C-j", ":wincmd j<CR>")
vim.keymap.set('n', "C-h", ":wincmd h<CR>")
vim.keymap.set('n', "C-l", ":wincmd l<CR>")
